# Test GET /beers
GET http://localhost:5003/api/v1/beers
Content-Type: application/json

###

# Test POST /beers
POST http://localhost:5003/api/v1/beers
Content-Type: application/json

{
  "name": "Nouvelle Bière",
  "type": "Blonde"
}
